workflows:
  android-dev-workflow-id:
    name: Android Dev Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      android_signing:
        - Coffix Keystore
      groups:
        - Android
        - Environment Dev
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Set up google-services.json
        script: |
          echo "$GOOGLE_SERVICES_JSON_DEV" | base64 --decode > "$CM_BUILD_DIR/android/app/src/dev/google-services.json"
      - name: Set up .env files
        script: |
          echo "API_BASE_URL=$API_BASE_URL" > "$CM_BUILD_DIR/.env.dev"
          echo "API_BASE_URL=$API_BASE_URL" > "$CM_BUILD_DIR/.env"
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build APK with Flutter
        script: |
          flutter build apk --release --flavor dev --target=lib/main_dev.dart
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
    publishing:
      firebase:
        # use this line to authenticate via service account
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT_DEV

        android:
          app_id: 1:659645318299:android:f3fda55702f3caac11323e

          # groups:
          # - internal
      email:
        recipients:
          - pajunar0@gmail.com
        notify:
          success: true
          failure: true

  ios-worklow-id:
    name: IOS Workflow
